kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: psql-pvc
  namespace: itus-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: psql-label
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-pvc
  namespace: itus-ns  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: ollama-label