kind: Secret
apiVersion: v1
metadata:
  name: itus-secrets
  namespace: itus-ns
data:
    DATABASE_PASSWORD: YmFua3Bhc3MxMjM= #base64 of bankpass123
    JWT_SECRET: aFVYY0h1TUptZlI3VHBYelR0RlFnMWxVVWJHaFJGVEhIYTNwK1FsdXBLdE5rcGhrYkJYZjRjbXQrNG4xMUFPeENTTHk4VjBGd3o5S2JIUFRJcDZ2Wmc9PQ==  #base64 of hUXcHuMJmfR7TpXzTtFQg1lUUbGhRFTHHa3p+QlupKtNkphkbBXf4cmt+4n11AOxCSLy8V0Fwz9KbHPTIp6vZg==
    POSTGRES_PASSWORD: YmFua3Bhc3MxMjM= #base64 of bankpass123