name: DevSecOps End To End Pipeline

on: 
    push:
        branches: [actions]

jobs:
    # CI (Continous Integration with Security Scanning)
    frontend-code-quality-and-depenedency:
        uses: ./.github/workflows/frontend-code-quality-dependency-check.yml

    backend-code-quality-and-depenedency:
        uses: ./.github/workflows/backend-code-quality-dependency-check.yml
        

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit
    
    dockerfile-scan:
        uses: ./.github/workflows/docker-lint.yml

    # tests:
    #     uses: ./.github/workflows/tests.yml

    # Build once the security scans and tests are complete
    build:
        needs: [frontend-code-quality-and-depenedency, backend-code-quality-and-depenedency, secrets-scan, dockerfile-scan]
        uses: ./.github/workflows/build-push.yml
        secrets: inherit

    # Image scan 
    trivy-for-frontend:
        needs: [build]
        uses: ./.github/workflows/front-docker-image-scan.yml
        secrets: inherit

    trivy-for-backend:
        needs: [build]
        uses: ./.github/workflows/back-docker-image-scan.yml
        secrets: inherit


    deploy-to-server:
        needs: [trivy-for-backend, trivy-for-frontend ]
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit

    