name: Docker Lint

on: 
    # workflow_call:
  push:
    branches: [actions]

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Validate Frontend Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: frontend/Dockerfile

            - name: Validate Backend Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: backend/Dockerfile