name: GitOps CI - Build & Push to DockerHub

on:
  push:
    branches: [gitops]
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
  workflow_dispatch:

permissions:
  contents: write

env:
  DOCKERHUB_REPO: sach990p/itus-eks

jobs:
  build-and-push:
    name: Build, Test & Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: frontend
            dockerfile: ./frontend/Dockerfile
            context: ./frontend
            manifest: k8s/frontend.yml
            image_name: sach990p/itus-frontend

          - service: backend
            dockerfile: ./backend/Dockerfile
            context: ./backend
            manifest: k8s/backend.yml
            image_name: sach990p/itus-backend


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true 

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

    #   - name: Build with Maven
    #     run: ./mvnw clean package -DskipTests -B

    #   - name: Run tests
    #     run: ./mvnw test -B
    #     continue-on-error: true

      - name: Set image tag
        id: tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.image_name }}:latest
            ${{ matrix.image_name }}:${{ steps.tag.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Kubernetes deployment manifest
        run: |
          sed -i "s|image: ${{ matrix.image_name }}:.*|image: ${{ matrix.image_name }}:${{ steps.tag.outputs.sha_short }}|" ${{ matrix.manifest }}


      - name: Commit updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ matrix.manifest }}
          git diff --staged --quiet || git commit -m "ci: update ${{ matrix.service }} image to ${{ steps.tag.outputs.sha_short }} [skip ci]"
          git pull origin gitops --rebase
          git push origin gitops